name: prima_studio
description: Project KWU

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  flutter_chat_ui: ^1.6.6
  firebase_core: ^2.1.1
  google_fonts: ^3.0.1
  flutter_chat_types: ^3.6.0
  persistent_bottom_nav_bar_v2: ^4.2.6
  carousel_slider: ^4.1.1
  transition: ^2.0.2
  cloud_firestore: ^4.0.5
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  pod_player: ^0.1.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_auth: ^4.1.3
  flutter_rating_bar: ^4.0.1
  modal_bottom_sheet: ^2.1.2
  cached_network_image: ^3.2.2
  google_sign_in: ^5.4.2
  url_launcher: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/Logo.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/ic_launcher/android/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
